server:
  port: 9090

spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  
  logging:
    level:
      org.springframework.r2dbc: DEBUG

ia:
  llama:
    url: ${IA_LLAMA_URL}
    key: ${IA_LLAMA_KEY}
  tts:
    url: ${IA_TTS_URL}
    key: ${IA_TTS_KEY}