# kubectl apply -f samuel-justiniani-23-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: samuel-justiniani-23-secret
  namespace: samuel-justiniani-23-namespace
type: Opaque
data:
  SPRING_R2DBC_URL: cjJkYmM6cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfNHhWdGZRSzNTUHZHQGVwLXJhc3B5LXdpbGRmbG93ZXItYWRzNWpkZTYuYy0yLnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL3NhbXVlbF9qdXN0aW5pYW5pXzIyP3NzbG1vZGU9cmVxdWlyZSZjaGFubmVsX2JpbmRpbmc9cmVxdWlyZQ==
  SPRING_R2DBC_USERNAME: bmVvbmRiX293bmVy
  SPRING_R2DBC_PASSWORD: bnBnXzR4VnRmUUszU1B2Rw==
  IA_LLAMA_URL: aHR0cHM6Ly9vcGVuLWFpMjEucC5yYXBpZGFwaS5jb20vY29udmVyc2F0aW9ubGxhbWE=
  IA_LLAMA_KEY: ZWMzMGNmNWQ5Mm1zaDdiMWRhNjE5ZWM4NDE1ZXAxOTU2MmVqc245ZTg5YTlmYzNlYWI=
  IA_TTS_URL: aHR0cHM6Ly9vcGVuLWFpLXRleHQtdG8tc3BlZWNoMS5wLnJhcGlkYXBpLmNvbS8=
  IA_TTS_KEY: ZWMzMGNmNWQ5Mm1zaDdiMWRhNjE5ZWM4NDE1ZXAxOTU2MmVqc245ZTg5YTlmYzNlYWI=

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode
