# kubectl apply -f samuel-justiniani-23-sercive.yml
apiVersion: v1
kind: Service
metadata:
  name: samuel-justiniani-23-service
  namespace: samuel-justiniani-23-namespace
spec:
  selector:
    app: samuel-justiniani-23-deployment
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
