# kubectl apply -f samuel-justiniani-23-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samuel-justiniani-23-deployment
  namespace: samuel-justiniani-23-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samuel-justiniani-23-deployment
  template:
    metadata:
      labels:
        app: samuel-justiniani-23-deployment
    spec:
      containers:
      - name: samuel-justiniani-23-container
        image: samuelimanol/as241s5_aej_23-be:1.0   # Imagen de tu Docker Hub
        ports:
        - containerPort: 9090
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: samuel-justiniani-23-secret
